# Development override for Docker Compose
version: '3.8'

services:
  api:
    build:
      target: base
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - PRELOAD_MODELS=false
      - RATE_LIMIT_PER_MINUTE=100
    volumes:
      - .:/app
      - ./models:/app/models
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
      - "9090:9090"

  worker:
    build:
      target: base
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - ./models:/app/models
    command: celery -A app.core.celery_app worker --loglevel=debug --concurrency=1

  beat:
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app