# Simplified Docker Compose for Deepfake Protection API
version: '3.8'

services:
  # Redis for caching and task queue
  redis:
    image: redis:7-alpine
    container_name: deepfake-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - deepfake-network

  # Main API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepfake-api
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEVICE=cpu
      - MAX_BATCH_SIZE=2
      - RATE_LIMIT_PER_MINUTE=30
    volumes:
      - ./logs:/app/logs
      - api_uploads:/app/uploads
      - api_temp:/app/temp
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    networks:
      - deepfake-network

  # Celery worker for batch processing
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deepfake-worker
    command: celery -A app.core.celery_app worker --loglevel=info --concurrency=1 --queues=batch_processing,model_management
    environment:
      - DEBUG=false
      - LOG_LEVEL=INFO
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEVICE=cpu
    volumes:
      - ./logs:/app/logs
      - worker_temp:/app/temp
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - deepfake-network

volumes:
  redis_data:
  api_uploads:
  api_temp:
  worker_temp:

networks:
  deepfake-network:
    driver: bridge